FROM python:3.11-slim-bookworm

# Install dependencies & Rust
# RUN apt-get update && apt-get install -y \
#     build-essential \
#     && apt-get clean \
#     && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy the requirements file first to leverage Docker cache
COPY src/requirements.txt .

# Install Python dependencies
RUN pip3 install --no-cache-dir -r requirements.txt

# Remove build dependencies to reduce image size
RUN apt-get update && apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

# Copy the entire project into the container
COPY src/ .

# Set environment variables for Docker runtime
ENV PYTHONUNBUFFERED=1
ENV RUNNING_IN_DOCKER=true

# Optional: Debugging tools (disable in production)
RUN ls -lsa
RUN pwd

# Default command to run the application
CMD ["python3", "main.py"]
